[package]
name = 'helloextendr'
version = '0.2.0'
edition = '2018'

[lib]
crate-type = [ 'staticlib' ]

[dependencies]
extendr-api = { git = "https://github.com/yutannihilation/extendr.git", branch = "tmp/minimal-libR-sys" }
polars = "*"
